api_version: 1
application: techism2-devel
default_expiration: 100d
handlers:
- {login: admin, script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py, url: /remote_api}
- {login: admin, script: djangoappengine/deferred/handler.py, url: /_ah/queue/deferred}
- {static_dir: static/admin/, url: /media/admin}
- {static_files: static/favicon.ico, upload: static/favicon.ico, url: /favicon.ico}
- {static_dir: static/, url: /static}
- {script: djangoappengine/main/main.py, url: /.*}
runtime: python
version: 5-devel
